# Generated by Django 5.0 on 2023-12-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='picture',
        ),
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
